package com.razboi.razboi.networking;


public enum ResponseType {
    OK, ERROR, USER_LOGGED_IN, PLAYER_WAITING, GAME_STARTED, START_GAME, YOUR_TURN, OPPONENT_WON, WORD_SUBMITTED, LETTER_SUBMITTED;
}
